# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CremaDevelopment
email: info@cremadevelopment.com
description: > # this means to ignore newlines until "baseurl:"
  CremaDevelopment "The good stuff goes to the top." "Come get your fix."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cremadevelopment.com" # the base hostname & protocol for your site
#twitter_username: CremaDevelopment
github_username:  CremaDevelopment

# Build settings
markdown: kramdown
